// <auto-generated />
namespace Atos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_NumberOfSeats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_NumberOfSeats));
        
        string IMigrationMetadata.Id
        {
            get { return "201904181620434_Add_NumberOfSeats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
